### ISSUE TITLE
Sub-text Below the Hero

### ISSUE THREAD

**Issue by reynoldsalec** [thinktandem/thinktandem.io#143]
**Description**

We have some sub-text copy for below the hero, but want to work a bit more on what our goals are for that section and what format we're presenting it in.

(See Body Content in [this Google Doc](https://docs.google.com/document/d/1souhtfBstup6t_CfMj7qFdAQhTnFuaCBc29sPT7nGY4/edit))

**Comment by reynoldsalec** [comment]
Meeting on Tuesday with @dbungard and @labboy0276 to refine our goals here, assign someone to finish it up/implement on site. Then we should be able to launch/retro/plan next Friday.

**Comment by dbungard** [comment]
**Copy we can play with or reject:**

Tandem is the agency that helps forward-thinking organizations like yours reach their goals because we value partnership and an efficient, repeatable process. 

What does that mean to you?


- We want to solve for your long-term goals, not just today's hot issue, Whether you’re in higher education, non-profit or a healthcare/corporate entity, we can help you travel the roadmap to conversions.
- We believe for us to win we need to act as an extension of your team and be invested in your success. Your results are our KPIs. 
- We don’t want to do one great thing for you. We want to continue to work with you and repeat your success with each new goal, efficiently - to save you time, budget and headaches.

Let’s talk.

**Comment by dbungard** [comment]
**Edited text**
>Whether you’re a university, non-profit, healthcare provider, or corporation, together we can find your roadmap to conversions using proven processes in digital strategy, design, and development. Let’s look towards your long-term goals while solving today's hot-button issue. Your results are how we measure our success. 
>[ What are your goals? ]

Agreed upon text ^ @labboy0276

**Comment by labboy0276** [comment]
OK @reynoldsalec @dbungard I added the sub hero, adjust the image so it loads faster, adjusted the hero for larger screens, etc.

https://pr-147-d55tnci-femv4bu3mqicm.us.platform.sh/
